IDENT_TYPES = {
        "IDENTIFIER",
        "TAG",
        'RATINGEXACT',
        'NOT',
        'STRINGEMPTY',
        'LPATH',
        'RPATH',
        'REGEX_OPEN',
        'REGEX_CLOSE',
        'REGEX',
        'BIND',
        'ID',
        'SUBTAG',
        'TYPE',
        'STATUS',
        'EXTRA',
        'LANGUAGE',
        'PROGLANG',
        'DATEMOD',
        'RATING',
        'CACHED',
        'DATECREATED',
        'DATE',
    }
PREFIX_TO_TYPE = {
        'PREFIX_ID': "ID",
        'PREFIX_SUBTAG': "SUBTAG",
        'PREFIX_TYPE': "TYPE",
        'PREFIX_STATUS': "STATUS",
        'PREFIX_EXTRA': "EXTRA",
        'PREFIX_LANGUAGE': "LANGUAGE",
        'PREFIX_PROGLANG': "PROGLANG",
        'PREFIX_DATEMOD': "DATEMOD",
        'PREFIX_RATING': "RATING",
        'PREFIX_CACHED': "CACHED",
        'PREFIX_DATECREATED': "DATECREATED",
}