import re
from functools import partial
from itertools import chain
from jn.editing import wrapped_test_query

concat = chain.from_iterable

test_dict = {
    "ID0001": {
        "text": "",
        "link": "",
        "type": "",
        "subtype": "",
        "tags": [""],
        "subtags": [""],
        "status": "",
        "dateCreated": "",
        "dateModified": "",
        "extra": {"language": "", "progLang": ""},
        "sorter": "",
        "id": "",
    },
    "ID0002": {},
    "ID0003": {},
    "ID0004": {},
    "ID0005": {},
    "ID0006": {},
    "ID0007": {},
    "ID0008": {},
    "ID0009": {},
    "ID0010": {},
    "ID0011": {},
    "ID0012": {},
    "ID0013": {},
    "ID0014": {},
    "ID0015": {},
    "ID0016": {},
    "ID0017": {},
    "ID0018": {},
    "ID0019": {},
    "ID0020": {},
    "ID0021": {},
    "ID0022": {},
    "ID0023": {},
    "ID0024": {},
    "ID0025": {},
    "ID0026": {},
    "ID0027": {},
    "ID0028": {},
    "ID0029": {},
    "ID0030": {},
    "ID0031": {},
    "ID0032": {},
}


def parse_and_output_all(query: str) -> tuple: ...


{
    "and_single": {
        "name": "and_single",
        "queries": ("a.b"),
        "status": "✔",
        "tokens": ([("IDENTIFIER", "a"), ("AND", "."), ("IDENTIFIER", "b")],),
        "ast": ("AND", ("TAG", ("STRING", "a")), ("TAG", ("STRING", "b"))),
        "raw_tree": {"AND": [{"TAG": {"STRING": "a"}}, {"TAG": {"STRING": "b"}}]},
        "tree": {"AND": [{"TAG": {"STRING": "a"}}, {"TAG": {"STRING": "b"}}]},
        "equivalent": lambda d: "a" in d["tags"] and "b" in d["tags"],
        "match_ids": [],
    },
    "and": {
        "name": "and",
        "queries": ("ab.cd"),
        "status": "✔",
        "tokens": ([("IDENTIFIER", "ab"), ("AND", "."), ("IDENTIFIER", "cd")],),
        "ast": ("AND", ("TAG", ("STRING", "ab")), ("TAG", ("STRING", "cd"))),
        "raw_tree": {"AND": [{"TAG": {"STRING": "ab"}}, {"TAG": {"STRING": "cd"}}]},
        "tree": {"AND": [{"TAG": {"STRING": "ab"}}, {"TAG": {"STRING": "cd"}}]},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "or_single": {
        "name": "or_single",
        "queries": ("a,b"),
        "status": "✔",
        "tokens": ([("IDENTIFIER", "a"), ("OR", ","), ("IDENTIFIER", "b")],),
        "ast": ("OR", ("TAG", ("STRING", "a")), ("TAG", ("STRING", "b"))),
        "raw_tree": {"OR": [{"TAG": {"STRING": "a"}}, {"TAG": {"STRING": "b"}}]},
        "tree": {"OR": [{"TAG": {"STRING": "a"}}, {"TAG": {"STRING": "b"}}]},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "or": {
        "name": "or",
        "queries": ("ab,cd"),
        "status": "✔",
        "tokens": ([("IDENTIFIER", "ab"), ("OR", ","), ("IDENTIFIER", "cd")],),
        "ast": ("OR", ("TAG", ("STRING", "ab")), ("TAG", ("STRING", "cd"))),
        "raw_tree": {"OR": [{"TAG": {"STRING": "ab"}}, {"TAG": {"STRING": "cd"}}]},
        "tree": {"OR": [{"TAG": {"STRING": "ab"}}, {"TAG": {"STRING": "cd"}}]},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "precedence": {
        "name": "precedence1",
        "queries": ("tagName1.tagName2,tagName3"),
        "status": "✔",
        "tokens": (
            [
                ("IDENTIFIER", "tagName1"),
                ("AND", "."),
                ("IDENTIFIER", "tagName2"),
                ("OR", ","),
                ("IDENTIFIER", "tagName3"),
            ],
        ),
        "ast": (
            "OR",
            ("AND", ("TAG", ("STRING", "tagName1")), ("TAG", ("STRING", "tagName2"))),
            ("TAG", ("STRING", "tagName3")),
        ),
        "raw_tree": {
            "OR": [
                {"AND": [{"TAG": {"STRING": "tagName1"}}, {"TAG": {"STRING": "tagName2"}}]},
                {"TAG": {"STRING": "tagName3"}},
            ]
        },
        "tree": {
            "OR": [
                {"AND": [{"TAG": {"STRING": "tagName1"}}, {"TAG": {"STRING": "tagName2"}}]},
                {"TAG": {"STRING": "tagName3"}},
            ]
        },
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "precedence": {
        "name": "precedence2",
        "queries": ("tagName1,tagName2.tagName3"),
        "status": "✔",
        "tokens": (
            [
                ("IDENTIFIER", "tagName1"),
                ("OR", ","),
                ("IDENTIFIER", "tagName2"),
                ("AND", "."),
                ("IDENTIFIER", "tagName3"),
            ],
        ),
        "ast": (
            "OR",
            ("TAG", ("STRING", "tagName1")),
            ("AND", ("TAG", ("STRING", "tagName2")), ("TAG", ("STRING", "tagName3"))),
        ),
        "raw_tree": {
            "OR": [
                {"TAG": {"STRING": "tagName1"}},
                {"AND": [{"TAG": {"STRING": "tagName2"}}, {"TAG": {"STRING": "tagName3"}}]},
            ]
        },
        "tree": {
            "OR": [
                {"TAG": {"STRING": "tagName1"}},
                {"AND": [{"TAG": {"STRING": "tagName2"}}, {"TAG": {"STRING": "tagName3"}}]},
            ]
        },
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_noval": {
        "name": "simple_noval",
        "queries": ("+extraTag1"),
        "status": "✔",
        "tokens": ([("PREFIX_EXTRA", "+"), ("IDENTIFIER", "extraTag1")],),
        "ast": ("EXTRA", ("NAME", ("STRING", "extraTag1"))),
        "raw_tree": {"EXTRA": {"NAME": {"STRING": "extraTag1"}}},
        "tree": {"EXTRA": {"NAME": {"STRING": "extraTag1"}}},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_extra": {
        "name": "simple_extra",
        "queries": ("+extraTag1:extraTagValue"),
        "status": "✔",
        "tokens": (
            [("PREFIX_EXTRA", "+"), ("IDENTIFIER", "extraTag1"), ("BIND", ":"), ("IDENTIFIER", "extraTagValue")],
        ),
        "ast": ("EXTRA", ("NAME", ("STRING", "extraTag1")), ("VALUE", ("STRING", "extraTagValue"))),
        "raw_tree": {"EXTRA": {"NAME": {"STRING": "extraTag1"}, "VALUE": {"STRING": "extraTagValue"}}},
        "tree": {"EXTRA": {"NAME": {"STRING": "extraTag1"}, "VALUE": {"STRING": "extraTagValue"}}},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_status": {
        "name": "simple_status",
        "queries": ("/statusName1"),
        "status": "✔",
        "tokens": ([("PREFIX_STATUS", "/"), ("IDENTIFIER", "statusName1")],),
        "ast": ("STATUS", ("STRING", "statusName1")),
        "raw_tree": {"STATUS": {"STRING": "statusName1"}},
        "tree": {"STATUS": {"STRING": "statusName1"}},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_rating": {
        "name": "simple_rating",
        "queries": ("*3.3"),
        "status": "✔",
        "tokens": ([("PREFIX_RATING", "*"), ("NUMBER", "3.3")],),
        "ast": ("RATING", ("VALUE", 3.3), ("INTERPRETATION", "AT_LEAST")),
        "raw_tree": {"RATING": {"VALUE": 3.3, "INTERPRETATION": "AT_LEAST"}},
        "tree": {"RATING": {"VALUE": 3.3, "INTERPRETATION": "AT_LEAST"}},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_tag": {
        "name": "simple_tag",
        "queries": ("tagName"),
        "status": "✔",
        "tokens": ([("IDENTIFIER", "tagName")],),
        "ast": ("TAG", ("STRING", "tagName")),
        "raw_tree": {"TAG": {"STRING": "tagName"}},
        "tree": {"TAG": {"STRING": "tagName"}},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_tag_subtag": {
        "name": "simple_tag_subtag",
        "queries": ("tagName1:subtagName1"),
        "status": "✔",
        "tokens": ([("IDENTIFIER", "tagName1"), ("BIND", ":"), ("IDENTIFIER", "subtagName1")],),
        "ast": ("TAG", ("STRING", "tagName1"), ("SUBTAG", ("STRING", "subtagName1"))),
        "raw_tree": {"TAG": {"STRING": "tagName1", "SUBTAG": {"STRING": "subtagName1"}}},
        "tree": {"TAG": {"STRING": "tagName1", "SUBTAG": {"STRING": "subtagName1"}}},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_embeddedregex": {
        "name": "simple_embeddedregex",
        "queries": ("〈[rR]eg.x\d,\d[[2,4]]-[A-Z]+\s?〉"),
        "status": "✔",
        "tokens": (
            [
                ("REGEX_EMBEDDED_OPEN", "〈"),
                ("REGEX_EMBEDDED", "[rR]eg.xd,d[[2,4]]-[A-Z]+s?"),
                ("REGEX_EMBEDDED_CLOSE", "〉"),
            ],
        ),
        "ast": ("TAG", ("REGEX", "[rR]eg.xd,d[[2,4]]-[A-Z]+s?")),
        "raw_tree": {"TAG": {"REGEX": "[rR]eg.xd,d[[2,4]]-[A-Z]+s?"}},
        "tree": {"TAG": {"REGEX": "[rR]eg.xd,d[[2,4]]-[A-Z]+s?"}},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_textregex": {
        "name": "simple_textregex",
        "queries": ("⸨[rR]eg.x\d,\d[[2,4]]-[A-Z]+\s?⸩"),
        "status": "✔",
        "tokens": (
            [("REGEX_TEXT_OPEN", "⸨"), ("REGEX_TEXT", "[rR]eg.xd,d[[2,4]]-[A-Z]+s?"), ("REGEX_TEXT_CLOSE", "⸩")],
        ),
        "ast": ("REGEX_TEXT", ("REGEX", "[rR]eg.xd,d[[2,4]]-[A-Z]+s?")),
        "raw_tree": {"REGEX_TEXT": {"REGEX": "[rR]eg.xd,d[[2,4]]-[A-Z]+s?"}},
        "tree": {"REGEX_TEXT": {"REGEX": "[rR]eg.xd,d[[2,4]]-[A-Z]+s?"}},
        "equivalent": lambda d: bool(re.search("[rR]eg.x\d,\d[[2,4]]-[A-Z]+\s?", d["text"])),
        "match_ids": [],
    },
    "simple_fullregex": {
        "name": "simple_fullregex",
        "queries": ("⦃[rR]eg.x\d,\d[[2,4]]-[A-Z]+\s?⦄"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: any(
            map(
                partial(re.search, pattern="[rR]eg.x\d,\d[[2,4]]-[A-Z]+\s?"),
                concat((d["extra"].keys(), d["extra"].values(), filter(partial(isinstance, class_or_tuple=str), d.values()))),
            )
        ),
        "match_ids": [],
    },
    "simple_linkregex": {
        "name": "simple_linkregex",
        "queries": ("«[rR]eg.x\d,\d[[2,4]]-[A-Z]+\s?»"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: bool(re.search("[rR]eg.x\d,\d[[2,4]]-[A-Z]+\s?", d["link"])),
        "match_ids": [],
    },
    "simple_type_subtype": {
        "name": "simple_type_subtype",
        "queries": ("%typeName:subtypeName"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (d["type"] == "typeName") and (d["subtype"] == "subtypeName"),
        "match_ids": [],
    },
    "simple_type": {
        "name": "simple_type",
        "queries": ("%typeName"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d["type"] == "typeName",
        "match_ids": [],
    },
    "simple_date_created": {
        "name": "simple_date_created",
        "queries": ("©2022-03-15"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d["dateModified"] >= "2022-03-15",
        "match_ids": [],
    },
    "simple_date_modified": {
        "name": "simple_date_modified",
        "queries": ("^2024-06-17"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d["dateModified"] >= "2024-06-17",
        "match_ids": [],
    },
    "simple_proglang": {
        "name": "simple_proglang",
        "queries": ("❱haskell"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d["extra"]["progLang"] == "haskell",
        "match_ids": [],
    },
    "simple_language": {
        "name": "simple_language",
        "queries": ("€EN"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d["extra"]["progLang"] == "EN",
        "match_ids": [],
    },
    "and_single_neg": {
        "name": "and_single_neg",
        "queries": ("~a.~b"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: ("a" not in d["tags"]) and ("b" not in d["tags"]),
        "match_ids": [],
    },
    "and_neg": {
        "name": "and_neg",
        "queries": ("~ab.~cd"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: ("ab" not in d["tags"]) and ("cd" not in d["tags"]),
        "match_ids": [],
    },
    "or_single_neg": {
        "name": "or_single_neg",
        "queries": ("~a,~b"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "or_neg": {
        "name": "or_neg",
        "queries": ("~ab,~cd"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "precedence_neg": {
        "name": "precedence_neg",
        "queries": ("~tag1.~tag2,~tag3"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_extra_neg": {
        "name": "simple_extra_neg",
        "queries": ("+~extraTag1"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_status_neg": {
        "name": "simple_status_neg",
        "queries": ("/~status1"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_rating_neg": {
        "name": "simple_rating_neg",
        "queries": ("*~4"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_tag_neg": {
        "name": "simple_tag_neg",
        "queries": ("~tagName1"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_tag_subtag_neg": {
        "name": "simple_tag_subtag_neg",
        "queries": ("tagName1:~subtagName"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_embeddedregex_neg": {
        "name": "simple_embeddedregex_neg",
        "queries": ("~〈someRegex〉"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_textregex_neg": {
        "name": "simple_textregex_neg",
        "queries": ("~⸨someRegex⸩"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_fullregex_neg": {
        "name": "simple_fullregex_neg",
        "queries": ("~⟪someRegex⟫"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_type_subtype_neg": {
        "name": "simple_type_subtype_neg",
        "queries": ("%typeName:~subtypeName"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_type_neg": {
        "name": "simple_type_neg",
        "queries": ("%~typeName"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_date_created_neg": {
        "name": "simple_date_created_neg",
        "queries": ("©~2022-03-15"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_date_modified_neg": {
        "name": "simple_date_modified_neg",
        "queries": ("^~2024-06-17"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_proglang_neg": {
        "name": "simple_proglang_neg",
        "queries": ("❱~haskell"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_language_neg": {
        "name": "simple_language_neg",
        "queries": ("€~EN"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_rating_exact": {
        "name": "simple_rating_exact",
        "queries": ("*~~4.0"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_date_created_exact": {
        "name": "simple_date_created_exact",
        "queries": ("©~~2019-04-06"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_date_modified_exact": {
        "name": "simple_date_modified_exact",
        "queries": ("^~~2021-07-10"),
        "status": "✔",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "and_single_opt": {
        "name": "and_single_opt",
        "queries": ("?a.?b"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "and_opt": {
        "name": "and_opt",
        "queries": ("?ab.?cd"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "or_single_opt": {
        "name": "or_single_opt",
        "queries": ("?a,?b"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "or_opt": {
        "name": "or_opt",
        "queries": ("?ab.?cd"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "or_opt": {
        "name": "or_opt",
        "queries": ("?ab.?cd"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "precedence_opt": {
        "name": "precedence_opt",
        "queries": ("?tag1.?tag2,?tag3"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_extra_opt": {
        "name": "simple_extra_opt",
        "queries": ("+?extraTagName:extraTagValue"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_status_opt": {
        "name": "simple_status_opt",
        "queries": ("/?statusName"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d["status"])) or (d["status"] == "statusName"),
        "match_ids": [],
    },
    "simple_rating_opt": {
        "name": "simple_rating_opt",
        "queries": ("*?4.1"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_tag_opt": {
        "name": "simple_tag_opt",
        "queries": ("?tagString"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_tag_subtag_opt": {
        "name": "simple_tag_subtag_opt",
        "queries": ("tagString:?subtagString"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_embeddedregex_opt": {
        "name": "simple_embeddedregex_opt",
        "queries": ("?〈someRegex〉"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_textregex_opt": {
        "name": "simple_textregex_opt",
        "queries": ("?⸨someRegex⸩"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_fullregex_opt": {
        "name": "simple_fullregex_opt",
        "queries": ("?⟪someRegex⟫"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_type_subtype_opt": {
        "name": "simple_type_subtype_opt",
        "queries": ("typeName:?subtypeName"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_type_opt": {
        "name": "simple_type_opt",
        "queries": ("%?typeName"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    # case_simple_date_created_opt = "©?"
    # case_simple_date_modified_opt = ""
    "simple_proglang_opt": {
        "name": "simple_proglang_opt",
        "queries": ("❱?python"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_language_opt": {
        "name": "simple_language_opt",
        "queries": ("€?EN"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "and_single_neg_opt": {
        "name": "and_single_neg_opt",
        "queries": ("?~a.?~b"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "and_neg_opt": {
        "name": "and_neg_opt",
        "queries": ("?~ab.cd"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "or_single_neg_opt": {
        "name": "or_single_neg_opt",
        "queries": ("?~a.?~b"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "or_neg_opt": {
        "name": "or_neg_opt",
        "queries": ("?~ab.cd"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "precedence_neg_opt": {
        "name": "precedence_neg_opt",
        "queries": ("?~tag1,?~tag2.tag3"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_extra_neg_opt": {
        "name": "simple_extra_neg_opt",
        "queries": ("?~extraName:extraValue"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_status_neg_opt": {
        "name": "simple_status_neg_opt",
        "queries": ("/?~statusName"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_rating_neg_opt": {
        "name": "simple_rating_neg_opt",
        "queries": ("*?~3.0"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_tag_neg_opt": {
        "name": "simple_tag_neg_opt",
        "queries": ("?~tagName"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_tag_subtag_neg_opt": {
        "name": "simple_tag_subtag_neg_opt",
        "queries": ("tagName:?~subtagName"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_embeddedregex_neg_opt": {
        "name": "simple_embeddedregex_neg_opt",
        "queries": ("?~〈someRegex〉"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_textregex_neg_opt": {
        "name": "simple_textregex_neg_opt",
        "queries": ("?~⸨someRegex⸩"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_fullregex_neg_opt": {
        "name": "simple_fullregex_neg_opt",
        "queries": ("?~⟪someRegex⟫"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_type_subtype_neg_opt": {
        "name": "simple_type_subtype_neg_opt",
        "queries": ("%typeName:?~subtypeName"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_type_neg_opt": {
        "name": "simple_type_neg_opt",
        "queries": ("%?~typeName"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d[""])) or (d[""]),
        "match_ids": [],
    },
    "simple_date_created_neg_opt": {
        "name": "simple_date_created_neg_opt",
        "queries": ("©?~2025-12-31"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d["date"])) or (d["dateCreated"] >= "2030-04-05"),
        "match_ids": [],
    },
    "simple_date_modified_neg_opt": {
        "name": "simple_date_modified_neg_opt",
        "queries": ("^?~2030-04-05"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: (not bool(d["date"])) or (d["dateModified"] >= "2030-04-05"),
        "match_ids": [],
    },
    "simple_proglang_neg_opt": {
        "name": "simple_proglang_neg_opt",
        "queries": ("❱?~python"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    "simple_language_neg_opt": {
        "name": "simple_language_neg_opt",
        "queries": ("€?~EN"),
        "status": " ",
        "tokens": (),
        "ast": {},
        "raw_tree": {},
        "tree": {},
        "equivalent": lambda d: d,
        "match_ids": [],
    },
    # # need to tokenize this as EXACT_NOT
    # "simple_rating_neg_exact": {
    #     "name": "simple_rating_neg_exact",
    #     "queries": ("*~~~3.0"),
    #     "status": "x",
    #     "tokens": (),
    #     "ast": {},
    #     "raw_tree": {},
    #     "tree": {},
    #     "equivalent": lambda d: d,
    #     "match_ids": [],
    # },
    # "simple_date_created_neg_exact": {
    #     "name": "simple_date_created_neg_exact",
    #     "queries": ("©~~~2023-05-31"),
    #     "status": "x",
    #     "tokens": (),
    #     "ast": {},
    #     "raw_tree": {},
    #     "tree": {},
    #     "equivalent": lambda d: d,
    #     "match_ids": [],
    # },
    # "simple_date_modified_neg_exact": {
    #     "name": "simple_date_modified_neg_exact",
    #     "queries": ("^~~~2024-11-21"),
    #     "status": "x",
    #     "tokens": (),
    #     "ast": {},
    #     "raw_tree": {},
    #     "tree": {},
    #     "equivalent": lambda d: d,
    #     "match_ids": [],
    # },
    # "simple_rating_neg_exact_opt": {
    #     "name": "simple_rating_neg_exact_opt",
    #     "queries": ("?~~~4.5"),
    #     "status": " ",
    #     "tokens": (),
    #     "ast": {},
    #     "raw_tree": {},
    #     "tree": {},
    #     "equivalent": lambda d: d,
    #     "match_ids": [],
    # },
    # "simple_date_created_neg_exact_opt": {
    #     "name": "simple_date_created_neg_exact_opt",
    #     "queries": ("©?~~~2022-10-13"),
    #     "status": " ",
    #     "tokens": (),
    #     "ast": {},
    #     "raw_tree": {},
    #     "tree": {},
    #     "equivalent": lambda d: d,
    #     "match_ids": [],
    # },
    # "simple_date_modified_neg_exact_opt": {
    #     "name": "simple_date_modified_neg_exact_opt",
    #     "queries": ("?~~~2020-05-18"),
    #     "status": " ",
    #     "tokens": (),
    #     "ast": {},
    #     "raw_tree": {},
    #     "tree": {},
    #     "equivalent": lambda d: d,
    #     "match_ids": [],
    # },
}

regex_special = ["[", "]", "{", "}", "-", "\\", "(", ")", "*", "^", "$", "=", ""]
